### ISSUE TITLE
Update stylesheets to use border-radius for specifying border-radius.

### ISSUE THREAD

**Issue by srih4ri** [projectfedena/fedena#11]
`Support for the prefixed version (-moz-border-radius) was removed in Gecko 13.0 (Firefox 13.0 / Thunderbird 13.0 / SeaMonkey 2.10).`
Says https://developer.mozilla.org/en-US/docs/CSS/border-radius

**Comment by tachyons** [comment]
Not fixed yet

**Comment by srih4ri** [comment]
@tachyons The latest release blog post on fedena blog is on [Apr 1 2015](http://www.fedena.com/blog/2015/04/fedena-3-4-2-release-notes.html), and last commit to this repo is on Jan 24, 2013. Doesn't look like this repo will be updated anymore.

**Comment by tachyons** [comment]
Yeah . no more update from Foradian . it is left for  the community

**Comment by abcsoeasy** [comment]
Yeah, the current fedena repo is really outdated in terms of ruby, gems,
rails,etc. Also it has some bugs.

**Comment by tachyons** [comment]
@abcsoeasy , yeah , but there already active  community attempts to port this to rails 4 . see https://github.com/SumitMunot/fedena-upgradation

**Comment by abcsoeasy** [comment]
@Aboobacker That is really great to hear., and a lot of thanks for putting
this for my notice. You know there were fedena LTS guys, who were not able
to continue their work due to lack of funds. I pray to Almighty that it,
should not happen this time.

**Comment by srih4ri** [comment]
@tachyons Are there any plans from @projectfedena or @foradian to co-ordinate community efforts around this project?
